{% set name = "barril" %}
{% set version = "1.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2f2ebd1049d81a78635e63e705a1c5ebefbe77298ce21e442a16800de9c5709

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - attrs >=18.1.0
    - numpy >=1.11.0
    - oop-ext >=0.2.4
    - python >=3.6

test:
  imports:
    - barril
    - barril.basic
    - barril.basic.format_float
    - barril.basic.fraction
    - barril.units
    - barril.units.scalar_validation
  requires:
    - pytest
    - pytest-mock
  commands:
    - pytest --pyargs barril

about:
  home: https://github.com/ESSS/barril
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to manage units for physical quantities

extra:
  recipe-maintainers:
    - igortg
    - kfasolin
    - lincrosenbach
    - nicoddemus
    - tadeu
    - jaimeambrus
