{% set name = "barril" %}
{% set version = "1.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9008f4806483958a31cde967b17c3f924db84464f9b755946176d46e972da94

build:
  skip: True  # [py35]
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - attrs >=18.1.0
    - numpy >=1.11.0
    - python
    - ruamel.ordereddict >=0.4.6  # [py27]

test:
  imports:
    - barril
    - barril.basic
    - barril.basic.format_float
    - barril.basic.fraction
    - barril.units
    - barril.units.scalar_validation
  requires:
    - pytest
    - pytest-mock
  commands:
    - pytest --pyargs barril

about:
  home: https://github.com/ESSS/barril
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to manage units for physical quantities

extra:
  recipe-maintainers:
    - igortg
    - kfasolin
    - lincrosenbach
    - nicoddemus
    - tadeu
    - jaimeambrus
