appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ymv9yVal1dq2ANPNrXpw0TEk8bGdA9LhVUdu/Kt7UMNu9c1wYNw0FBCyDK7SJReUZG54N2B1fZbLTvtOixJuszeB6yGNKoxKOpaa1G7HB2DZ93c6sY+bqFnxqhJuE5Z4zn8B2qoCytkEdclT/b2Vk4r8pZfJ5D66o+4EAAoWGfiLATdev5VxnrOnAKEQi7izljk53ShvLh2EuSdVvpTGpaf5iLriUgMiyVcS6G1yx6Wzhgq6WptqXtMXLQOWTK7Bjulzb5YJoIWsl+4rIxDK5MYYtycSYaAdGTTK1PJrSvaHKLhh3MG7vDfdbO19/da/2+pJHHshoiAPo8RC2hRJaeqe7nxTxGWsvFWACjoOXtV10C/3K8Snvy12ATDAKWUoLXLviT0I2IfrRESfLpIvoj+im/N3BjSGttWK6WKbBCJfc4SwRWlbj3ytp4cfdowjXUScUDcEVUGFdlH3odGMh9mWRlNK17i+a6YYNkRyBFgXnKP4dXc1Aq0p3zUZ88Ji6srksHVcswrK9T2ByRfIk3B9gDLtDUr2P4cXdtzluHTyf3jkzOg7v0swB0JfKP8wRGxSQlzOKlg3GEcINab1jqeAHXBF0dannOY/vIkcIQGZy1xqj75xz46QgVGLGyEH+ziihXB0mvsUkZCSj/KClAG1N0Pv7rEjVSVVoT5Nkbo=}
